package com.example.data.remote

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.example.data.model.AuthUser
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.UserProfileChangeRequest
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext

class FirebaseAuthService(private val context: Context) {
    private val TAG = "FirebaseAuthService"
    private var auth: FirebaseAuth? = null

    private val _currentUser = MutableStateFlow<AuthUser?>(null)
    val currentUser: StateFlow<AuthUser?> = _currentUser.asStateFlow()

    init {
        try {
            if (FirebaseApp.getApps(context).isEmpty()) {
                try {
                    FirebaseApp.initializeApp(context)
                } catch (e: Exception) {
                    Log.w(TAG, "Eager FirebaseApp.initializeApp: ${e.message}")
                }
            }

            if (FirebaseApp.getApps(context).isNotEmpty()) {
                auth = FirebaseAuth.getInstance()
                auth?.addAuthStateListener { fbAuth ->
                    val user = fbAuth.currentUser
                    _currentUser.value = user?.toAuthUser()
                    Log.d(TAG, "Auth state changed: user=${user?.email ?: user?.uid}")
                }
                _currentUser.value = auth?.currentUser?.toAuthUser()
            } else {
                Log.w(TAG, "FirebaseApp is not initialized yet.")
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error initializing FirebaseAuth: ${e.message}")
        }
    }

    fun isAuthAvailable(): Boolean = auth != null

    fun getCurrentFirebaseUser(): FirebaseUser? = auth?.currentUser

    suspend fun signUpWithEmail(
        email: String,
        pass: String,
        displayName: String?
    ): Result<AuthUser> = withContext(Dispatchers.IO) {
        val fbAuth = auth ?: return@withContext Result.failure(IllegalStateException("Firebase Auth is not initialized"))
        try {
            val result = fbAuth.createUserWithEmailAndPassword(email.trim(), pass).await()
            val user = result.user ?: return@withContext Result.failure(IllegalStateException("Failed to create user account"))

            if (!displayName.isNullOrBlank()) {
                val profileUpdates = UserProfileChangeRequest.Builder()
                    .setDisplayName(displayName.trim())
                    .build()
                user.updateProfile(profileUpdates).await()
            }

            val authUser = user.toAuthUser()
            _currentUser.value = authUser
            Result.success(authUser)
        } catch (e: Exception) {
            Log.e(TAG, "Email sign-up failed: ${e.message}")
            Result.failure(e)
        }
    }

    suspend fun signInWithEmail(
        email: String,
        pass: String
    ): Result<AuthUser> = withContext(Dispatchers.IO) {
        val fbAuth = auth ?: return@withContext Result.failure(IllegalStateException("Firebase Auth is not initialized"))
        try {
            val result = fbAuth.signInWithEmailAndPassword(email.trim(), pass).await()
            val user = result.user ?: return@withContext Result.failure(IllegalStateException("User not found"))
            val authUser = user.toAuthUser()
            _currentUser.value = authUser
            Result.success(authUser)
        } catch (e: Exception) {
            Log.e(TAG, "Email sign-in failed: ${e.message}")
            Result.failure(e)
        }
    }

    suspend fun signInWithGoogle(activityContext: Context): Result<AuthUser> = withContext(Dispatchers.IO) {
        val fbAuth = auth ?: return@withContext Result.failure(IllegalStateException("Firebase Auth is not initialized"))
        try {
            val credentialManager = CredentialManager.create(activityContext)

            // Try to find default web client id generated by google-services or use project client id
            val resId = activityContext.resources.getIdentifier("default_web_client_id", "string", activityContext.packageName)
            val webClientId = if (resId != 0) activityContext.getString(resId) else "991162599567-dgjska9msq0keo4om1bhejub29ae0f44.apps.googleusercontent.com"

            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setAutoSelectEnabled(false)
                .setServerClientId(webClientId)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val response = credentialManager.getCredential(
                request = request,
                context = activityContext
            )

            val credential = response.credential
            if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken
                val authCredential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult = fbAuth.signInWithCredential(authCredential).await()
                val user = authResult.user ?: return@withContext Result.failure(IllegalStateException("Google Sign-In user is null"))
                val authUser = user.toAuthUser()
                _currentUser.value = authUser
                Result.success(authUser)
            } else {
                Result.failure(IllegalStateException("Unexpected credential type: ${credential.type}"))
            }
        } catch (e: Exception) {
            Log.e(TAG, "Google Sign-In failed: ${e.message}")
            Result.failure(e)
        }
    }

    suspend fun signInAnonymously(): Result<AuthUser> = withContext(Dispatchers.IO) {
        val fbAuth = auth ?: return@withContext Result.failure(IllegalStateException("Firebase Auth is not initialized"))
        try {
            val result = fbAuth.signInAnonymously().await()
            val user = result.user ?: return@withContext Result.failure(IllegalStateException("Anonymous user is null"))
            val authUser = user.toAuthUser()
            _currentUser.value = authUser
            Result.success(authUser)
        } catch (e: Exception) {
            Log.e(TAG, "Anonymous sign-in failed: ${e.message}")
            Result.failure(e)
        }
    }

    suspend fun sendPasswordReset(email: String): Result<Unit> = withContext(Dispatchers.IO) {
        val fbAuth = auth ?: return@withContext Result.failure(IllegalStateException("Firebase Auth is not initialized"))
        try {
            fbAuth.sendPasswordResetEmail(email.trim()).await()
            Result.success(Unit)
        } catch (e: Exception) {
            Log.e(TAG, "Password reset failed: ${e.message}")
            Result.failure(e)
        }
    }

    fun signOut() {
        try {
            auth?.signOut()
            _currentUser.value = null
        } catch (e: Exception) {
            Log.e(TAG, "Sign out error: ${e.message}")
        }
    }

    private fun FirebaseUser.toAuthUser(): AuthUser {
        return AuthUser(
            uid = uid,
            email = email,
            displayName = displayName ?: email?.substringBefore("@"),
            photoUrl = photoUrl?.toString(),
            isAnonymous = isAnonymous
        )
    }
}
